name: Docker Image CI/CD

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: "marwannayman"
  DOCKER_PASSWORD: "dckr_pat_PgAmz85dZJUI0Df1ZGimhNVRxqs"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{env.DOCKER_USERNAME}}
          password: ${{env.DOCKER_PASSWORD}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{env.DOCKER_USERNAME}}/admin-view:latest