name: Docker Image CI/CD

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${ { secrets.DOCKER_USERNAME } }
  DOCKER_PASSWORD: ${ { secrets.DOCKER_TOKEN } }

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{env.DOCKER_USERNAME}}
          password: ${{env.DOCKER_PASSWORD}}

      - name: Build Docker Image
        run: |
          docker build -t admin-view .

      - name: Push Docker Image
        run: |
          docker tag admin-view ${{env.DOCKER_USERNAME}}/admin-view:latest
          docker push ${{env.DOCKER_USERNAME}}/admin-view:latest