name: Docker CI/CD

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_USERNAME: "marwanaymann"
  DOCKER_PASSWORD: "dckr_pat_PgAmz85dZJUI0Df1ZGimhNVRxqs"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{env.DOCKER_USERNAME}}
          password: ${{env.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: |
          docker build -t admin-view ../../
      - name: Push Docker Image
        run: |
          docker tag admin-view ${{env.DOCKER_USERNAME}}/admin-view:latest
          docker push ${{env.DOCKER_USERNAME}}/admin-view:latest

